#if !canImport(ObjectiveC)
import XCTest

extension BimapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BimapTests = [
        ("testInitEmpty", testInitEmpty),
        ("testKeySubscript", testKeySubscript),
        ("testRemoveAll", testRemoveAll),
        ("testRemoveKey", testRemoveKey),
        ("testRemoveValue", testRemoveValue),
        ("testUpdateKey", testUpdateKey),
        ("testUpdateValue", testUpdateValue),
        ("testValueSubscript", testValueSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BimapTests.__allTests__BimapTests),
    ]
}
#endif
